name: conj-stress-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - numpy=2.3.1
  - pandas=2.3.1
  - scikit-learn=1.7.0
  - matplotlib=3.10.3
  - tqdm=4.67.1
  - requests=2.32.4
  - pubchempy=1.0.4
  - rdkit=2025.03.4
  - shap=0.48.0
  - xgboost=3.0.2
  - openpyxl=3.1.5
  - pip
  - setuptools
  - wheel